### ISSUE TITLE
PMM - Binance Connector not working as it should - stuck after few hours

### ISSUE THREAD

**Issue by PKBO** [hummingbot/dashboard#162]
### Describe the bug

Hello, i have an issue on PMM.  Tested multiple times with mirror changes, but everytime bot will end with stucked orders without cancelling them by timelimit or so.  Error log says not enought budget to open position, but bot is started with 5% reserve on both sides and it has amount needed to maintain initial number of orders.

Config: buy_amounts_pct:
- 0.25
- 0.25
- 0.25
buy_spreads:
- 0.0006
- 0.0009
- 0.0012
candles_config: []
connector_name: binance
controller_name: pmm_simple
controller_type: market_making
cooldown_time: 300.0
executor_refresh_time: 180.0
id: BTC1_0.1
leverage: 1
manual_kill_switch: null
position_mode: HEDGE
sell_amounts_pct:
- 0.25
- 0.25
- 0.25
sell_spreads:
- 0.0006
- 0.0009
- 0.0012
stop_loss: 0.008
take_profit: 0.0004
take_profit_order_type: 2
time_limit: 300
total_amount_quote: 4800
trading_pair: BTC-USDT
trailing_stop:
  activation_price: 0.018
  trailing_delta: 0.002

### Steps to reproduce bug

1.  Set PMM with low spread (3+3 / 4+4 per side)
2. Let it run and wait few hours, or till some big movements. 
3. 
4.

**Comment by rapcmia** [comment]
hi @PKBO im running a bot with almost same setup and will try to reproduce. Would it be possible to share any of your log files as well to help investigate? thank you

**Comment by rapcmia** [comment]
Ran a bot for 2hrs 30mins using the attached config (modified since i dont have that much amount to use 😅 )
- Orders created and cancelled ok `early_stop`
- Orders filled, opened executor
  - Created TP limit order, some got filled `take_profit`
  - Some got cancelled due to time_limit (300s) therefore market order created  `time_limit`
  ![image](https://github.com/user-attachments/assets/cd26e4a0-5201-448b-8925-c8210411b1ac)
- Started with balance of 220
  - Set total_amount_quote to 50, (i think i have more than enough reserved balance, thts why i cant reproduce the `not enough budget to open position` )
  - Script to create 2 order levels 

config:
```
candles_config: []
connector_name: binance
controller_name: pmm_simple
controller_type: market_making
cooldown_time: 300.0
executor_refresh_time: 180.0
id: test_issue162
leverage: 1
manual_kill_switch: null
position_mode: HEDGE
buy_amounts_pct:
- 0.25
- 0.25
buy_spreads:
- 0.0006
- 0.0009
sell_amounts_pct:
- 0.25
- 0.25
sell_spreads:
- 0.0006
- 0.0009
stop_loss: 0.008
take_profit: 0.0004
take_profit_order_type: 2
time_limit: 300
total_amount_quote: 50
trading_pair: NOT-USDT
trailing_stop:
  activation_price: 0.018
  trailing_delta: 0.002
```

Log file:
[07192024.zip](https://github.com/user-attachments/files/16312536/07192024.zip)
