### ISSUE TITLE
Bug Report Unable login with crendentials.yaml

### ISSUE THREAD

**Issue by liho00** [hummingbot/dashboard#173]
### Describe the bug

 Unable login with crendentials.yaml, cant register, cant logout

### Steps to reproduce bug

using docker deploy hummingbot/dashboard:latest

credentials.yml
```
# This only works if you change the env variable in the docker-compose.yml
credentials:
  usernames:
    admin:
      email: test@gmail.com
      name: test
      logged_in: False
      password: $2b$12$I32ZqZ6Od3nUptrwfXtiiutlCfJ5/UQzPyQq7DivqwKUBixy8qoka
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - admin@admin.com
  - test@gmail.com
  ```
  
  
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/45edfa2b-2a47-4b29-be13-0ec8f925884b">
