### ISSUE TITLE
Every Page is empty on the 1st run

### ISSUE THREAD

**Issue by ArjunZe** [hummingbot/dashboard#204]
### Describe the bug

On the 1st run, visited http://10.0.0.10:8501/Credentials and I see nothing on the UI except `About this Page`. This is the behavior with every page.

![image](https://github.com/user-attachments/assets/f67e4c77-4da5-4910-bfca-aaa18aa0d2fa)

### Steps to reproduce bug

1. Follow steps from https://github.com/hummingbot/deploy?tab=readme-ov-file#installation
2. Change BACKEND_API_PORT to 8502 from default 8000 for both backend-api and dashboard
3. run setup.sh

Issue is not observed with default port 8000

**Comment by david-hummingbot** [comment]
@ArjunZe Can you post the docker-compose.yml file with the port changes?

**Comment by ArjunZe** [comment]
> @ArjunZe Can you post the docker-compose.yml file with the port changes?

Here it is.
```
services:
  dashboard:
    container_name: dashboard
    image: hummingbot/dashboard:latest
    ports:
      - "8501:8501"
    environment:
        - AUTH_SYSTEM_ENABLED=True
        - BACKEND_API_HOST=backend-api
        - BACKEND_API_PORT=8502
        - BACKEND_API_USERNAME=admin
        - BACKEND_API_PASSWORD=admin
    volumes:
      - ./credentials.yml:/home/dashboard/credentials.yml
      - ./pages:/home/dashboard/frontend/pages
    networks:
        - emqx-bridge
  backend-api:
    container_name: backend-api
    image: hummingbot/backend-api:latest
    ports:
      - "8502:8000"
    volumes:
      - ./bots:/backend-api/bots
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - BROKER_HOST=emqx
      - BROKER_PORT=1883
      - USERNAME=admin
      - PASSWORD=admin
    networks:
      - emqx-bridge
  emqx:
    container_name: hummingbot-broker
    image: emqx:5
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.local
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.local]
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-etc:/opt/emqx/etc
    ports:
      - "1883:1883"  # mqtt:tcp
      - "8883:8883"  # mqtt:tcp:ssl
      - "8083:8083"  # mqtt:ws
      - "8084:8084"  # mqtt:ws:ssl
      - "8081:8081"  # http:management
      - "18083:18083"  # http:dashboard
      - "61613:61613"  # web-stomp gateway
    networks:
      emqx-bridge:
        aliases:
          - node1.emqx.local
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5

networks:
  emqx-bridge:
    driver: bridge

volumes:
  emqx-data: { }
  emqx-log: { }
  emqx-etc: { }

```

**Comment by david-hummingbot** [comment]
Ok, I see the issue. You actually don't need to change this part - 

```
    environment:
        - AUTH_SYSTEM_ENABLED=True
        - BACKEND_API_HOST=backend-api
        - BACKEND_API_PORT=8502
        - BACKEND_API_USERNAME=admin
        - BACKEND_API_PASSWORD=admin
```
Change it back to the default 8000 since it's using Docker's internal network and it's still mapped to port 8000

The change you made here will allow you to access the backend api at port `8502` on your local machine ex. `localhost:8502/docs`
```
 backend-api:
    container_name: backend-api
    image: hummingbot/backend-api:latest
    ports:
      - "8502:8000"
```
